### ISSUE TITLE
How to move a namespace to another tenant without delete and recreate

### ISSUE THREAD

**Issue by shadow625** [projectcapsule/capsule#1131]
# Describe the feature
In some situation, we wanna change the tenant of one particular namespace due to team responsibility changed. Also we would want the service under that namesapce keeps running. In other term: make the namespace change transparently to the service.

How would the new interaction with Capsule look like

1. Cluster has two tenants belong to different team. 
2. Team responsibility changed, one service's custodian need change to another team.  
3. Namespace belong to `TenantA` need to change to `TenantB`
4. Cluster Admin changed the tenant of this namespace
5. Service keeps running during this procedure.

# Expected behavior
Service keeps running during this procedure. transfer the ownership of namespace transparently. ❤️

**Comment by prometherion** [comment]
I think this is already possible, since Capsule relies on two components here:

1. Namespace's OwnerReference pointing to the Tenant defintion
2. Namespace's label `capsule.clastix.io/tenant`

If a cluster administrator changes the Namespace by matching the other Tenant with the proper UID and name, along with the labels, the Namespace can be easily transferred.

```
$: kubectl get tenants
NAME    STATE    NAMESPACE QUOTA   NAMESPACE COUNT   NODE SELECTOR   AGE
solar   Active                     1                                 46s
wind    Active                     1                                 39s

$: kubectl get ns -l capsule.clastix.io/tenant --show-labels
NAME     STATUS   AGE   LABELS
ns-bar   Active   28s   capsule.clastix.io/tenant=wind,kubernetes.io/metadata.name=ns-bar
ns-foo   Active   36s   capsule.clastix.io/tenant=solar,kubernetes.io/metadata.name=ns-foo

$: kubectl get tnt wind -o jsonpath='{.metadata.uid}'
0df8e9ee-5f6f-40a4-897d-b80d349ca36f%

$: kubectl edit ns ns-foo
# hacking UID and labels

$: kubectl get tenants
NAME    STATE    NAMESPACE QUOTA   NAMESPACE COUNT   NODE SELECTOR   AGE
solar   Active                     0                                 2m22s
wind    Active                     2                                 2m15s
```

@shadow625 please, let me know if this could work fine, or if you're expecting something else: e.g.: I didn't test if a Tenant owner (e.g.: `alice`) who has multiple Tenants assigned (e.g.: `solar`, `wind`) has self-service capabilities to transfer a Namespace from a Tenant to another one.

**Comment by oliverbaehler** [comment]
@prometherion just admins, i can consider thid for documentation

**Comment by shadow625** [comment]
Thank you heaps @prometherion ,  this solved my issue.

**Comment by prometherion** [comment]
@shadow625 you're welcome, wondering if you could contribute to our Website and share these steps to move ownership of a Namespace between Tenants, this is the repositoryhttps://github.com/projectcapsule/website

It would be a nice first contribution, sharing is gold!

**Comment by shadow625** [comment]
So sorry for wasting my first chance to contribute this project, it's just too busy last two weeks, really love what you built 🚀 thank you team 🫰
