### ISSUE TITLE
How to uninstall capsule done with YAML installer

### ISSUE THREAD

**Issue by kgphani** [projectcapsule/capsule#797]
Hi, 

I have installed capsule using YAML installer. Is there also any YAML that can be applied to uninstall capsule?  
Also, we have to document the below. Can you please provide the details for the same.
- What gets installed with Capsule like Webhooks, CRDs, Secrets etc. 
- What is their role in Capsule
- Capsule versions vs. supported versions of Kubectl, Helm and clients
- Steps for uninstalling Capsule for both deployment options: YAML & Helm
- Steps for verification after cleanup

**Comment by prometherion** [comment]
You can use the same YAML file to uninstall Capsule, although it would be destructive action:

- In the single YAML file the required resources such as Deployment, Service, ClusterRoleBinding, etc. are available as well as the CustomResourceDefinitions such as Tenant, CapsuleConfiguration, and GlobalTenantResources.
- When deleting all these manifests, also the CRDs will be removed, thus provoking a cascading effect on all the Tenants, which will cause Namespaces to be removed too
- Furthermore, since the removal of the Capsule manager Deployment, the webhooks would start failing, creating a deadlock in the cluster since the `Fail` policy in most of the webhooks

With that said, we always suggested giving a try to Capsule through the Helm Chart since it allows overcoming these limitations and solving the uninstall process.

The single YAML installation must be used only by users who are aware of what they're doing, and it's not providing all the safety nets which Helm is offering.

If we can document this better it would be great, I'm marking this issue as a Documentation one and I'm open in accepting your Pull Request in addressing this!

**Comment by Rajdeep1311** [comment]
I can help but I am quite new to open-source. I want to assist you with this issue

**Comment by maxgio92** [comment]
Hi @Rajdeep1311, welcome! You could start by proposing the documentation that is missing right now with respect of what @kgphani asked for.
What do you think?

**Comment by Rajdeep1311** [comment]
@maxgio92 Surely, I can try

**Comment by Rajdeep1311** [comment]
I think I have to read more about Capsule can you suggest me some resources? @maxgio92

**Comment by prometherion** [comment]
@Rajdeep1311 please, don't take this personally.

There's a README in the repository, as well a documentation website linked to it. If you look for `capsule Kubernetes multi tenancy` on Google or any other search engine you'll end up in a pletora of materials.

Documentation is always a good starting point to contribute to a project, that's true.

I'm always open to any report about unclarity in regard to documentation, getting started materials, etc. but this doesn't seem the case, or, if it is and you're feeling it, may I ask you what should we do to improve this?

**Comment by Rajdeep1311** [comment]
It's nothing like that... It's completely alright, I am a beginner. It's nothing rude on your side. Thanks for suggesting sir.

**Comment by oliverbaehler** [comment]
Since our supported way of installation is via helm, we will close this issue.
