### ISSUE TITLE
Enhancement: Modify OnCreate namespace hook to check Namespace Existence by Name

### ISSUE THREAD

**Issue by SergK** [projectcapsule/capsule#868]
# Describe the feature

In the current implementation of the IsFull function in tenant_func.go, the function checks if the tenant is full based on the number of namespaces. This approach, while functional, does not provide the flexibility to check for the existence of a specific namespace by its name. So instead of getting the error: `Error from server (AlreadyExists): namespaces "NAMESPACE" already exists` we have an issue with `Quota exceeded.`

# What would the new user story look like?

We can modify the OnCreate() handler to include an additional check for the existence of a namespace. The function (e.g., Exists()) should iterate over in.Status.Namespaces and check if a namespace with the given name exists. If a match is found, the function should return `true`. The function should return `false` if no match is found after checking all namespaces and the quota is exceeded.

```
func (in *Tenant) Exists(namespaceName string) bool {
    for _, namespace := range in.Status.Namespaces {
        if namespace == namespaceName {
            return true
        }
    }
    return false
}
```

OnCreate() handler can return nil, and we can rely on an error from Kubernetes.

This enhancement will provide a more flexible and precise way to check for namespace existence within a tenant.

# Expected behavior
1. Create a namespace `test` for the tenant with the namespace quota equal to 1.
2. Try to create a namespace with the name `test` once again, and you should get the error that the namespace already exists

**Comment by prometherion** [comment]
I am figuring out a possible drawback of this approach, such as exfiltrating existing Namespaces.

Rather than iterating over the namespaces stored in the Tenant definition status, we could reuse the local client cache, and check the status of the Namespace:

1. if it doesn't exist, we do a proxy pass to the next handlers
2. if it exists and is bound to a non-owned Tenant, do a proxy pass to the next handlers
3. if it exists and is bound to a Tenant owned by the user or any group whose part, returning 403

The rationale here is that a user can have one or more Tenants, and Capsule allows creating Namespaces without a specific prefix.

Does it sound acceptable to you, @SergK?

**Comment by SergK** [comment]
@prometherion thank you for the feedback. I'm all on your side for technical implementation.
